[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run data_analysis_streamlit_app.py --server.port=$PORT --server.address=0.0.0.0 --server.maxUploadSize=2000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
